truncate table ti_building

SET IDENTITY_INSERT ti_building ON
insert into ti_building(build_id, prompl_id, build_name) values(1,1,'Здание АБК (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(2,2,'Пожарный БОКС (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(3,1,'Здание СЭБ (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(4,2,'Здание Связи (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(5,3,'ЦПК (Калинина, 25)')
insert into ti_building(build_id, prompl_id, build_name) values(6,2,'Здание АБК (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(7,1,'Здание КИП (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(8,1,'Здание АТЦ (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(9,1,'Столовая Березка (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(10,1,'Здание СБ (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(11,1,'Здание АВП (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(12,1,'Здание Главного склада (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(13,1,'Здание склада ГСМ (arz)')
insert into ti_building(build_id, prompl_id, build_name) values(15,2,'Блок-Бокс ЛИСКЦ (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(16,5,'Волгаталеком')
insert into ti_building(build_id, prompl_id, build_name) values(17,3,'ЦПК (Лаборатория Сварки)')
insert into ti_building(build_id, prompl_id, build_name) values(18,6,'ГРС ПЕШЕЛАНЬ')
insert into ti_building(build_id, prompl_id, build_name) values(19,4,'Здание АБК (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(20,4,'Гараж на 10 автомобилей (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(21,4,'Здание ЭБ (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(22,4,'БЭС (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(23,4,'Здание ТЗП (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(24,4,'Здание РЭБ (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(25,4,'КПП с проходной (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(26,4,'КПП (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(27,4,'Столовая (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(28,4,'КТП АВО газа (narz)')
insert into ti_building(build_id, prompl_id, build_name) values(29,2,'Здание ЭБ (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(30,2,'Здание РЭБ (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(31,2,'Здание ТЗП (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(32,2,'КПП с проходной (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(33,2,'КПП (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(34,2,'Гараж (luk)')
insert into ti_building(build_id, prompl_id, build_name) values(35,2,'Столовая (luk)')
SET IDENTITY_INSERT ti_building OFF
go
