truncate table ti_serv

SET IDENTITY_INSERT ti_serv ON
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(1,'Служба КИПиА, АСУ, телемеханики','arz_gKIP','KIP')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(2,'Служба ЭВС','arz_gEVS','EVS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(3,'Служба ИТ','arz_gSIT','SIT')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(4,'АУП','arz_gAUP','AUP')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(5,'СБУ','arz_gSBU','SBU')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(6,'ДС','arz_gDISP','DISP')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(7,'Медпункт','arz_gMED','MED')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(8,'Служба ОТ и ПБ','arz_gOT','OT')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(9,'Служба ПО','arz_gSPO','SPO')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(10,'Служба ГРС','arz_gGRS','GRS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(11,'Служба ЗоК','arz_gZOK','ZOK')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(12,'ЛЭС','arz_gLES','LES')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(13,'Группа недвижимого имущества','arz_gIMU','IMU')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(14,'Отдел кадров','arz_gOK','OK')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(15,'Служба Связи','arz_gSS','SS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(16,'ПЛНК','arz_gPLNK','PLNK')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(17,'СМУ','arz_gSMU','SMU')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(18,'Отделение защиты имущества','arz_gSB','SB')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(19,'Экономическая группа','arz_gEKON','EKON')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(20,'АТЦ','arz_gATC','ATC')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(21,'Служба МТС','arz_gMTS','MTS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(22,'Служба КС, Р, ТП и ТН','arz_gOKS','OKS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(23,'Столовая Березка','arz_gBEREZKA','BEREZKA')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(24,'Общежитие','arz_gOBSH','OBSH')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(25,'КС-24 ЛЭГ','arz_gLES','LES')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(26,'ГКС Лукояновская','arz_gKS24','GKS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(28,'КС-24 Группа Энерговодоснабжен','arz_gEVS','EVS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(29,'КС-24 АТЦ','arz_gATC','ATC')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(30,'ЦПК','arz_gCPK','-')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(31,'Учебная лаборатория КИП','arz_gCPK','-')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(32,'Учебная лаборатория ЛЭС-ГРС','arz_gCPK','-')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(33,'АУП ЦПК','arz_gCPK','-')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(34,'Хозгруппа (ЛПУМГ)','arz_gHOZ','HOZ')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(35,'Группа по эксплуатации компрессорных агрегатов и вспомогательного оборудования','arz_gKS24','GKS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(36,'АВП','arz_gLES','LES')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(37,'Группа по ремонту компрессорных агрегатов и вспомогательного оборудования','arz_gKS24','GKS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(38,'КС Новоарзамасская','arz_gNARZ','NARZ')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(41,'КС-24 Группа ЗоК','arz_gZOK','ZOK')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(42,'КС-24 Участок связи','arz_gSS','SS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(43,'ГКС Новоарзамасская','arz_gNARZ','NARZ')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(44,'КС-02 Служба КИПиА, АСУ А и ТМ','arz_gKIP','KIP')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(45,'КС-02 Служба ЭВС','arz_gEVS','EVS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(46,'КС-02 Служба ИТ','arz_gSIT','SIT')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(47,'КС-02 Служба связи','arz_gSS','SS')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(48,'КС-02 Служба ПО','arz_gSPO','SPO')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(49,'КС-02 Служба ЗоК','arz_gZOK','ZOK')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(50,'КС-02 Служба безопасности','arz_gSB','SB')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(51,'КС-02 АТЦ','arz_gATC','ATC')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(53,'Нижегородский отряд охраны','arz_gNOO','NOO')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(54,'ЦПК-Преподаватели','cpk_gTEACH','TEACH')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(55,'ЦПК-СБУ','cpk_gSBU','SBU')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(56,'ЦПК-Аппарат управления','cpk_gAUP','AUP')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(57,'ЦПК-Компьютерный класс','cpk_gSIT','SIT')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(58,'Химическая лаборатория','arz_gOT','OT')
insert into ti_serv(serv_id,serv_name,serv_grp,serv_cat) values(59,'Первичная профсоюзная организация','arz_gPPO','PPO')
SET IDENTITY_INSERT ti_serv OFF
go