truncate table ti_places

SET IDENTITY_INSERT ti_places ON
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(11,1,7,'207','Инженеры КИП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(12,3,1,'305','Инженеры СИТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(13,2,7,'-','-')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(14,8,8,'207','Инженеры ОТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(15,4,1,'312','')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(16,15,3,'-','ЛАЗ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(17,5,1,'201','Бухгалтеры')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(18,19,1,'304','Экономисты')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(19,15,4,'-','Руководитель группы')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(20,5,1,'202','Бухгалтеры')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(21,3,1,'305','СИТ-СКЛАД')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(22,20,8,'201','Учебный класс по БДД')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(23,5,1,'205','Бухгалтеры')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(24,6,1,'308','Диспетчеры')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(25,3,6,'-','Серверная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(26,1,6,'211','Инженеры КИПиА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(27,3,1,'309','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(28,23,9,'-','Столовая Березка')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(29,9,2,'-','-')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(30,12,3,'-','Участок ЭСГ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(31,3,1,'302','Инженеры ИТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(32,18,10,'-','начальник СБ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(33,4,8,'203','-')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(34,1,7,'206','-')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(35,3,1,'-','Учебный класс')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(36,11,3,'3','Специалисты ЗоК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(37,12,3,'-','мастера ЛЭС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(38,3,6,'301','ГЩУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(39,14,3,'-','Отдел Кадров')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(40,15,3,'203','Начальник службы связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(41,15,3,'-','АТС ИСКРА SI 2000')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(42,15,3,'-','ЛАЗ-COM')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(43,4,11,'-','Кабинет директора')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(44,8,11,'-','Начальник службы ОТ и ПБ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(45,16,11,'-','Лаборатория ПЛНК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(46,16,11,'-','начальник ПЛНК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(47,17,11,'-','мастера СМУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(48,1,7,'-','Лаборатория по ремонту Газовых')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(49,1,6,'208','инженеры КИП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(50,1,7,'202','инженер-метролог')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(51,1,7,'207','инженер ТМ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(52,1,7,'203','метрологи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(53,1,7,'-','Лаборатория по ремонту ротацио')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(54,1,7,'209a','руководител лаборатории по рем')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(55,1,7,'206','Лаборатория по ремонту эл.счет')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(56,2,7,'211','инженеры ЭВС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(57,19,1,'303','экономисты')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(58,7,1,'101','Медпункт')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(59,20,8,'204','Начальник АТЦ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(60,9,7,'201','Начальник СПО')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(61,21,12,'1','Кладовщики')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(62,8,8,'209','Специалист по ГО')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(63,22,8,'206','инженеры ОКС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(65,8,6,'2','Хим.лаборатория')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(66,2,6,'207','Специалисты ЭВС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(67,26,6,'301','ГЩУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(68,15,4,'-','Кабинет АТС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(69,15,4,'2','ЛАЗ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(70,20,6,'106','Автодиспетчер')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(71,10,3,'-','начальник службы ГРС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(72,34,8,'208','Художник')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(73,13,3,'-','Группа недвижимого имущества')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(74,10,3,'-','инженеры ГРС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(75,4,3,'-','Юрисконсульт')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(76,20,8,'204','Автодиспетчер АК-2')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(77,5,1,'203','Главный бухгалтер')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(78,1,7,'209','Инженеры КИП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(79,20,8,'205','Автодиспетчер АК-1')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(80,26,6,'204','начальник ГКС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(81,2,7,'210','Начальник ЭВС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(82,5,1,'205','бухгалтеры')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(83,19,1,'311','экономист')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(84,22,8,'206','Начальник ОКС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(86,21,13,'-','Операторская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(87,24,5,'-','Заведующий общежитиями')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(88,4,11,'-','Приемная директора')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(89,15,3,'204','Факс')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(90,36,11,'-','Зам.начальника ЛЭС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(91,3,1,'307','Начальник ДС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(92,12,3,'-','Начальник ЛЭС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(93,21,8,'203','специалисты МТС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(94,21,8,'202','начальник МТС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(95,1,6,'210','вед.инженер КИП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(96,25,6,'203','мастера ЛЭГ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(97,37,6,'206','инженер по ремонту')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(98,1,7,'208','Начальник КИП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(99,21,6,'212','кладовщик')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(100,38,19,'-','-')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(101,4,1,'310','приемная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(102,26,6,'204','Приемная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(103,26,6,'204','Начальник КС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(104,15,3,'2','инженеры связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(105,11,6,'209','Мастер ЗОК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(106,1,7,'-','Коридор здания')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(107,20,8,'-','Коридор здания АТЦ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(108,3,1,'301','Копиры')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(109,26,6,'-','Студия')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(110,3,11,'-','Актовый зал')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(111,3,5,'-','Серверная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(112,1,15,'-','Блок-Бокс')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(113,3,6,'20?','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(114,3,16,'-','ЛАЗ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(118,30,17,'-','Учебный класс')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(119,30,5,'-','Разные помещения ЦПК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(120,1,18,'-','-')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(121,3,1,'10?','Инверторная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(122,4,11,'-','Зам.директора Калинин')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(123,23,9,'-','VIP-Зал')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(124,44,19,'222','Не использовать')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(125,50,26,'1','Помещение охраны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(126,50,26,'2','Комната отдыха')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(127,50,25,'2','Начальник смены')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(128,50,25,'3','Пост охраны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(129,45,20,'17','Электрощитовая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(130,51,20,'8','Помещение технического обслужи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(131,51,20,'12','Диспетчерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(132,51,20,'13','Комната отдыха шоферов')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(133,51,20,'21','Помещение главного механика')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(134,46,20,'26','Помещение связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(135,45,22,'7','Мастерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(136,45,22,'13','Помещение обслуживающего персо')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(137,45,22,'12','Кабинет начальика ЭСН')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(138,45,22,'11','Комната отдыха')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(139,45,22,'10','Операторная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(140,45,22,'9','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(141,45,22,'8','Помещение релейных панелей')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(142,45,22,'1','Помещение ЗРУ - 10 кВ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(143,45,22,'2','Помещение КТПСН и вторичных сб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(144,45,22,'3','Помещение щита постоянного ток')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(145,46,22,'5','Помещение связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(146,38,21,'1','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(147,44,21,'2','Помещение службы КИП и А')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(148,45,21,'6','Электрощитовая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(149,45,21,'12','Коридор')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(150,45,21,'10','Помещение КТП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(151,45,24,'1','КТП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(152,45,24,'2','Электрощитовая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(153,44,24,'4','Щитовая КИП и А')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(154,38,24,'6','Участок расконсервации двигате')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(155,38,24,'8','Слесарный участок')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(156,38,24,'12','Участок сварочных работ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(157,38,24,'18','Помещение для машинистов ГКЦ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(158,46,24,'19','Помещение связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(159,45,24,'22','Помещение дежурных электриков')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(160,44,24,'27','Мастерская и лаборатория служб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(161,44,24,'36','Помещение инженера по метролог')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(162,44,24,'37','Помещение инженера ТМ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(163,38,24,'42','Комната службы КЦ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(164,38,24,'43','Комната службы ЛЭС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(165,44,24,'13','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(166,38,24,'16','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(167,45,24,'17','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(168,58,24,'35','Хроматографическая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(169,58,24,'38','Измерительная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(170,58,24,'39','Аналитическая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(171,58,24,'41','Химлаборатория')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(172,47,19,'106','Мастерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(173,47,19,'109','Кладовая участка связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(174,47,19,'110','Монтерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(175,47,19,'112','Радиоузел')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(176,47,19,'113','Комната ИТР')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(177,45,19,'115','Электрощитовая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(178,50,19,'124','Комната приема пищи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(179,50,19,'116','Центральный пост охраны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(180,21,19,'101','Кладовщица')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(181,50,19,'102','Зам начальника Арзамасского от')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(182,43,19,'103','Медпункт')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(184,47,19,'209','Выпрямительная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(185,47,19,'207','Коммутаторная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(186,47,19,'206','Комната приема пищи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(187,47,19,'214','Начальник узла связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(188,47,19,'213','АТС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(189,47,19,'212','Кроссовая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(190,47,19,'211','ЛАЗ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(191,47,19,'210','Комната ПС РРЛ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(192,38,19,'217','Инженер сменный руководитель г')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(193,44,19,'216','Электрощитовая АСУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(194,38,19,'201','Главный щит управления')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(195,38,19,'200','Комната приема пищи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(196,44,19,'202','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(197,44,19,'203','Инженер АСУ, КИПиА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(198,44,19,'204','Ведущий инженер КИП и А, руков')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(199,47,19,'308','Студия связи сетевых совещаний')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(200,43,19,'317','Касса')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(201,43,19,'306','Учебный класс')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(202,43,19,'305','Инженер группы эксплуатации')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(203,43,19,'304','Мастер ЛЭГ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(204,43,19,'303','Зам начальника ГКС начальник К')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(205,43,19,'301','Приемная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(206,43,19,'302','Начальник ГКС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(207,43,19,'318','Комната отдыха')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(208,49,19,'316','Группа ЗОК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(209,46,19,'314','Инженер ИТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(210,45,19,'313','Инженер энергетик руководитель')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(211,45,19,'312','Инженер ЭТВС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(212,45,19,'311','Инженеры ЭТВС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(213,43,19,'310','Архив')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(214,43,19,'9','ПРУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(215,43,19,'12','Коридор')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(216,43,27,'125','Экспедиторская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(217,43,27,'124','РУ-0,4 кВ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(218,43,27,'106','Сервировочная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(219,43,27,'103','Вестибюль')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(220,43,23,'1','Операторная ТЗП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(221,48,19,'3','Гараж')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(222,34,8,'101','Хозгруппа')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(223,18,6,'7','Специалист СБ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(224,20,8,'204','Начальник автоколонны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(225,15,3,'2','инженер ЛСС и АУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(226,11,3,'5','монтерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(227,4,3,'-','зам.директора')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(228,58,19,'15','Химлаборатория')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(229,45,28,'1','КТП АВО Газа')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(230,7,1,'102','Врач - руководитель медпункта')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(231,4,1,'207','Зал заседаний')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(232,26,6,'205','Сменный инженер')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(233,3,6,'205','Сменный инженер')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(234,55,5,'108','Бухгалтерия')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(236,54,5,'301','Лаборатория связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(237,54,5,'502','Методический кабинет')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(238,56,5,'111','')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(239,57,5,'305','Группа ИТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(240,54,5,'-','Кабинет сварки')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(241,54,5,'101','Лаборатория ЛЭС-ГРС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(242,54,5,'201','Лаборатория электрооборудовани')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(243,54,5,'110','Лаборатория ЭХЗ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(244,54,5,'113','Кабинет газ.хозяйства')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(245,54,5,'403','Лаборатория КИПиА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(246,54,5,'109','Препараторская ГПМ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(247,54,17,'-','Кабинет сварки')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(248,54,5,'203','Лаборатория ГПА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(249,54,5,'306','Препараторская лаб. связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(250,54,5,'3','Мастерская стропольщиков')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(251,56,5,'105','Заместитель начальника ЦПК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(252,56,5,'105','Секретарь')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(253,54,5,'106','Безопасное произ-во работ ГПМ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(254,54,5,'303','Кабинет сварки')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(255,54,5,'103','Кабинет ГРС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(256,54,5,'102','Кабинет ЛЭС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(257,56,5,'107','Кабинет ОТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(258,54,5,'202','Кабинет электрооборудования')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(259,57,5,'205','Склад')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(260,54,5,'206','Тренажер КИПиА-ГПА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(261,54,5,'302','Кабинет связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(262,57,5,'304','Серверная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(263,54,5,'401','Лаборатория метрологии')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(264,54,5,'402','Лаборатория САУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(265,54,5,'405','Кабинет КИПиА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(266,57,5,'404','Студия видеоконференцсвязи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(267,54,5,'501','Кабинет ПБ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(268,57,5,'503','Актовый зал')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(269,54,5,'2','Каб. Эксплуатация ГПМ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(270,54,5,'1','Каб. Обслуживание автомобилей')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(271,56,5,'105','Начальник ЦПК')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(272,4,1,'310','Заместитель директора')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(273,3,3,'-','Начальник СИТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(274,26,29,'1','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(275,26,31,'1','Операторная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(276,26,33,'1','Помещение охраны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(277,26,33,'2','Комната отдыха')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(278,26,35,'125','Экспедиторская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(279,26,35,'124','РУ – 0,4 кВ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(280,26,35,'106','Сервировочная ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(281,26,35,'105','Гардероб для посетителей')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(282,26,34,'26','Помещение связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(283,26,34,'21','Электрощитовая')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(284,26,34,'12','Помещение ТО и Р автомобилей')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(285,26,34,'14','Диспетчерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(286,26,34,'15','Комната отдыха шоферов')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(287,26,34,'16','Бытовые помещения')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(288,26,34,'22','Помещение главного механика')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(289,26,34,'28','Учебный класс')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(290,26,34,'29','Кабинет начальника пожарной ох')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(291,26,29,'3','Помещение службы КИПиА')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(292,26,29,'12','Коридор')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(293,26,32,'6','Командир дежурной смены')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(294,26,32,'3','Комната отдыха')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(295,26,32,'1','Помещение ЦПО')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(296,26,32,'2','Помещение поста охраны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(297,26,32,'7','Вестибюль ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(298,26,32,'9','Помещение для изготовления про')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(299,26,32,'10','Кабинет начальника СБ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(300,26,32,'11','Кабинет инженера ТСО')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(301,26,32,'12','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(302,26,32,'17','Электрощитовая (ЛВС)')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(303,26,30,'1','КТП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(304,26,30,'3','Электрощитовая. Тамбур')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(305,26,30,'4','Кладовая КИП')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(306,26,30,'6','Участок расконсервации двигате')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(307,26,30,'8','Слесарный участок')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(308,26,30,'12','Участок сварочных работ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(309,26,30,'13','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(310,26,30,'16','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(311,26,30,'17','Гардероб')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(312,26,30,'19','Помещение связи ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(313,26,30,'18','Помещение для машинистов ГКЦ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(314,26,30,'22','Помещение службы ЭВС')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(315,26,30,'27','Мастерская КИПиА, АСУ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(316,26,30,'38','Помещение экологов ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(317,26,30,'40','Аппаратная')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(318,26,30,'41','Диспетчерская')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(319,26,30,'29','Помещение калибровки СИ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(320,26,30,'36','Хроматографическая ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(321,26,30,'37','Химлаборатория')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(322,26,6,'101','Инженер-Химик')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(323,26,4,'10','Мастерская связи')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(324,53,1,'-','Помещение охраны')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(325,9,20,'-','Командир отделения')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(326,8,3,'-','Начальник ОТ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(327,8,3,'-','Начальник службы ОТи ПБ')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(328,7,6,'109','Медицинский кабинет')
insert into ti_places(place_id,serv_id,build_id,kab_n,kab_name) values(329,26,6,'109','Кабинет предрейсовых осмотров')
SET IDENTITY_INSERT ti_places OFF
go