truncate table ti_types

SET IDENTITY_INSERT ti_types ON
insert into ti_types(type_id,type_name) values(1,'Компьютер персональный')
insert into ti_types(type_id,type_name) values(2,'Компьютер (Notebook)')
insert into ti_types(type_id,type_name) values(3,'Компьютер (PocketPC)')
insert into ti_types(type_id,type_name) values(4,'CPU')
insert into ti_types(type_id,type_name) values(5,'Компьютер в составе оборудования')
insert into ti_types(type_id,type_name) values(6,'Компьютер SUN')
insert into ti_types(type_id,type_name) values(7,'Сервер Intel')
insert into ti_types(type_id,type_name) values(8,'Сервер SUN')
insert into ti_types(type_id,type_name) values(10,'Сервер в составе оборудования')
insert into ti_types(type_id,type_name) values(11,'Принтер лазерный A3')
insert into ti_types(type_id,type_name) values(12,'Принтер Лазерный А4')
insert into ti_types(type_id,type_name) values(13,'МФУ')
insert into ti_types(type_id,type_name) values(14,'Принтер струйный')
insert into ti_types(type_id,type_name) values(15,'Копировальный Аппарат A3')
insert into ti_types(type_id,type_name) values(16,'Копировальный Аппарат A4')
insert into ti_types(type_id,type_name) values(17,'Сканнер')
insert into ti_types(type_id,type_name) values(18,'Фотоаппарат')
insert into ti_types(type_id,type_name) values(19,'Проектор мультимедийный')
insert into ti_types(type_id,type_name) values(20,'Ламинатор')
insert into ti_types(type_id,type_name) values(21,'Переплетная машина')
insert into ti_types(type_id,type_name) values(22,'Шреддер (уничтожитель)')
insert into ti_types(type_id,type_name) values(23,'Экран для проектора')
insert into ti_types(type_id,type_name) values(24,'Принтер матричный')
insert into ti_types(type_id,type_name) values(25,'Плоттер')
insert into ti_types(type_id,type_name) values(26,'Плоттер режущий')
insert into ti_types(type_id,type_name) values(27,'Аудио-световая аппаратура')
insert into ti_types(type_id,type_name) values(28,'Телекоммуникационное оборудование')
insert into ti_types(type_id,type_name) values(29,'Библиотека Ленточная')
insert into ti_types(type_id,type_name) values(30,'Маршрутизатор')
insert into ti_types(type_id,type_name) values(31,'Модем xDSL')
insert into ti_types(type_id,type_name) values(32,'Модем Аналог')
insert into ti_types(type_id,type_name) values(33,'Коммутатор')
insert into ti_types(type_id,type_name) values(34,'Межсетевой Экран')
insert into ti_types(type_id,type_name) values(35,'Конвертер')
insert into ti_types(type_id,type_name) values(36,'Шлюз VoIP')
insert into ti_types(type_id,type_name) values(37,'Телефон VoIP')
insert into ti_types(type_id,type_name) values(38,'ИБП (ups)')
insert into ti_types(type_id,type_name) values(39,'Кондиционер')
insert into ti_types(type_id,type_name) values(40,'Монитор')
insert into ti_types(type_id,type_name) values(41,'DKVM')
insert into ti_types(type_id,type_name) values(42,'WIFI')
insert into ti_types(type_id,type_name) values(43,'Принт-сервер')
insert into ti_types(type_id,type_name) values(44,'TerminalServer')
insert into ti_types(type_id,type_name) values(45,'Web-Камера')
insert into ti_types(type_id,type_name) values(46,'Приборы')
insert into ti_types(type_id,type_name) values(47,'Видеокамера')
insert into ti_types(type_id,type_name) values(48,'HDD-External Drive')
insert into ti_types(type_id,type_name) values(49,'Оборудование ВКС')
insert into ti_types(type_id,type_name) values(50,'Мебель')
insert into ti_types(type_id,type_name) values(51,'Комплекс (программно-аппаратный)')
insert into ti_types(type_id,type_name) values(52,'Дисковый массив')
insert into ti_types(type_id,type_name) values(53,'Контроллер')
insert into ti_types(type_id,type_name) values(54,'Тренажер')
insert into ti_types(type_id,type_name) values(55,'Планшет')
insert into ti_types(type_id,type_name) values(56,'Телевизор')
SET IDENTITY_INSERT ti_types OFF
go