truncate table ti_mark

SET IDENTITY_INSERT ti_mark ON
insert into ti_mark(mark_id,mark_name,enlarge_id) values(19,'Cisco 1601',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(20,'Cisco 2500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(21,'Cisco 2821',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(22,'Cisco 3745',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(23,'Cisco 4000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(24,'Cisco ASA 5510',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(25,'Cisco Catalyst 2940',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(26,'Cisco Catalyst 2950',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(27,'Cisco Catalyst 2960-24',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(28,'Cisco Catalyst 3750',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(29,'Cisco IP Phone 7911G',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(30,'Cisco IP Phone 7970G',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(32,'Cronyx PCM2',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(33,'D-LINK DES-3226S',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(34,'D-LINK DMC-1000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(35,'DELL Optiplex 5133\Gsl',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(36,'DLINK DMC-1910R',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(37,'DLINK DMC-1910T',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(38,'DLINK DMC-920R',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(39,'DLINK DMC-920T',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(40,'DT6400',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(41,'Epson DFX-8000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(42,'Epson EMP-170',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(43,'Epson EMP-755',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(44,'Epson FX-1170',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(45,'Epson LX-1050',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(46,'Fellowes SPLA3',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(47,'FG-PAM-SAN-4Eth',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(48,'FG-VIP-FXO4',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(49,'GBS',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(50,'Geha Primo 800',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(51,'GladWork VS702CG',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(52,'GladWork VS705C',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(53,'HP 4670',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(54,'hp 7400c',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(55,'hp 7500c',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(2,'Компьютер-ноутбук',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(3,'-',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(4,'',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(5,'Cisco 1601',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(6,'3COM 3С 16475-ME',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(13,'Ricoh Aficio SP1000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(15,'BENQ',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(16,'Canon IXUS-500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(17,'CANON IXUS-60',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(62,'HP LJ 2300',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(63,'HP LJ 5',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(72,'HP LJ 4V/MV',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(73,'HP NETSERVER LH 6000 U3',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(74,'HP Proliant DL 140',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(75,'HP Proliant ML 350 G5',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(76,'HP StorageWorks 1/8 G2 Tape Autoloader',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(77,'IBM E-Server  xSeries 346 (НЕ ИСПОЛЬЗОВАТЬ)',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(78,'IBM e-Server xSeries 346',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(79,'IDC',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(80,'Lexmark T420',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(81,'Lexmark W820',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(82,'MB 116',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(83,'MB2212',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(84,'MB5815',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(85,'model',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(59,'HP LJ 1200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(60,'HP LJ 1320',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(87,'Nateks FG-VIP-FXO4',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(88,'Nateks FG-VIP-FXS2',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(89,'Philips Sematrans',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(90,'Proliant 1600',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(96,'Roland CX-24',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(97,'RX5009',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(98,'RX5220',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(99,'RX5317-II',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(100,'SAMSUNG MFU SCX-4100',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(101,'SAMSUNG ML1615',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(102,'Sun Ultra Enterprise 1',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(103,'Sun Ultra Enterprise 3500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(104,'Sun UltraEnteprise 3000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(105,'SunFire V240',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(106,'TAINET T-336Cx',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(107,'US Robotics',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(108,'Xerox Phazer 3120',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(109,'Zyxel Prestige 841',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(110,'Zyxel Prestige 841c',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(112,'Коммутатор Cisco Catalyst 2960 (НЕ ИСПОЛЬЗОВАТЬ)',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(113,'Принтер Epson Stylus Photo R340',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(114,'Принтер HP DJ 3940',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(115,'Сanon LBP 1120 (Не использовать)',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(116,'HP Proliant DL160 G5 P/N:445204-421',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(117,'HP Proliant DL180 G5 P/N:47064-722',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(118,'HP ScanJet 5530 (Q3871A)',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(119,'APC Smart UPS RT 10000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(120,'APC Smart UPS 700',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(121,'APC Smart UPS 1400',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(122,'APC Smart UPS 600',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(124,'MGE Pulsar EX10',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(125,'APC Smart UPS RT 2000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(126,'APC Smart UPS 2200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(127,'Настольный Компьютер',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(128,'APC Smart UPS 1000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(129,'APC Smart UPS SC 1500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(130,'APC Smart UPS 750',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(131,'POWERMAN Back Pro 1000 Plus',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(132,'HP Proliant ML370T04',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(133,'Panasonic KX-FLM653RU',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(134,'DAIKIN MA90/04',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(135,'Compaq NX6310',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(136,'DLINK DKVM-IP1',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(137,'DLINK-AP2100+',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(138,'Eaton Powerware 9390',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(139,'DLINK DP100+',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(140,'SUN NTS',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(141,'ADAM-4577',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(142,'Aficio MP3010',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(143,'Ricoh Aficio MP 3010',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(144,'HP LJ 9050N',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(164,'HP Compaq dc5800s MT',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(165,'Samsung ML2015',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(166,'Aquarius Std_MSP S20 S34',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(167,'Iiyama Pro Lite E2003 WSV PL2000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(168,'Acer AL 1917N',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(169,'HP kw 4400 Workstation',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(170,'Kraftway Credo KC57',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(171,'NEC AccuSync LCD 93 VM',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(172,'APC Back UPS CS 650',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(173,'NEC MultiSync LCD 195 VXM',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(174,'BENQ ET 0005-B',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(175,'HP DJ D2563',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(176,'HP Compaq dx2400 E2200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(177,'HP TFT L1950g',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(178,'Acer AL 1716',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(179,'Fujitsu Siemens Computers Esprimo P3510',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(180,'Kraftway Express 100',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(181,'D-link DES 1018 DG',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(182,'3COM 16471',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(183,'Ricoh Aficio SP C420dn',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(184,'NEC MultiSync LCD 225WXM',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(185,'HP Color LJ 2605dn ',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(186,'126-CC5',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(187,'DELL E198FP',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(188,'APC Smart PRO UPS Tripp Lite',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(189,'D-LINK DES 1026G',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(190,'Benq G700 LCD',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(191,'DEPO Storm 1250Q1',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(192,'Slideaway LCD KVM Switch CL 1208',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(193,'HP Proliant DL380 G5',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(194,'Altusen KL 1508',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(195,'APC Smart UPS RT 5000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(196,'APC Battary Pack',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(197,'Fujitsu Siemens RX 200 S4',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(198,'HP TFT LP 2065',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(199,'WS-C2960-24PC-L',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(200,'Cisco Catalyst 3570',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(201,'Sun Ultra 20 M2',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(202,'Simatic Rack PC 547B',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(203,'DLINK-AP2000+',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(204,'Canon 990IS',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(205,'DLINK DCS-2100',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(206,'HP ScanJet G4010',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(207,'Acer Aspire 2000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(208,'HP ScanJet 4670',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(209,'AXIS 232D Network Dome Camera',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(210,'Acer  Aspire 5810TG-354G32Mi',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(211,'HP 6730B ',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(212,'HP 2400',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(146,'DeIl Opti Plex 755DT C2D E7200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(147,'D-LINK DGS-1016D',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(148,'Surecom EP-805SX',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(149,'Ricoh Aficio SP3200sf',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(150,'Cisco 3845',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(151,'ИЦ-1500БП',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(152,'ZyXEL U-336S',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(153,'HP Proliant DL360R05 5130',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(154,'HP DC7700 CMT',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(155,'HP TFT LP1965',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(156,'HP TFT 7600',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(157,'APC Smart UPS 3000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(158,'APC Smart UPS 450BA',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(159,'APC Smart UPS SC 420',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(160,'HP Compaq dc7800p',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(161,'Samsung SyncMaster 743N',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(162,'APC Back UPS RS 650',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(230,'Panasonic HDC-HS20EE-K',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(231,'Seagate 500gb Free Agent Desk',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(232,'Esprimo P5925EPA',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(233,'Ruggedcom RSG2100',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(234,'Ruggedcom RS416',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(235,'SICAM miniRTU',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(236,'Ricoh Aficio SP3300DN',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(237,'Genicom 3480',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(238,'Zyxel P793H',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(239,'DLINK-2100AP',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(240,'Eaton 3000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(241,'Неизвестная модель',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(242,'ASUS F3J',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(243,'ASUS K52JC-SX069R',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(214,'Ricoh Aficio FX-200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(215,'ATEN KVMP CL5716M-A',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(216,'SunFire V445',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(217,'HP Proliant DL 320 G6',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(218,'Intel SR2500ALLX',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(219,'iROBO IPC-600-F',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(220,'IBM Server',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(221,'Klondake Server',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(222,'DELL Latitude 110L',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(223,'Toshiba Satellite A300D',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(224,'Fluke Networks OptiView Series III Integrated Network Analizyer',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(246,'Canon IXUS 95IS',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(247,'Samsung 710 TFT',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(248,'APC Switched Rack PDU',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(249,'Sun StorageTek 2540 FC Array',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(250,'HP Storage Works MSA 2000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(251,'Cisco 2610',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(252,'HP LJ 3010',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(253,'HP DL360 G5',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(254,'HP DL320 G6',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(255,'ASUS K52JC',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(226,'Epson EB-X62',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(227,'ASUS PRO64V',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(258,'MSA 2312',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(260,'RTU327-E1-R2-M2',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(290,'HP LJ 5200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(291,'Connekt 18708000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(292,'APC Smart UPS RT 3000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(293,'Panasonic CS-C18GKD/CU-C18G KD',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(294,'ASUS VE246',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(295,'Sony HDR-HC5E',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(296,'Hitachi CP-X275/RX-60',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(297,'Hitachi CP-Х445D',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(298,'Logitech C170',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(299,'Genius Trek 310',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(300,'Microsift Life Cam 720p',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(301,'Logitech Webcam C600',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(302,'ViewSonic PJ255D',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(303,'Panasonic CS-A24BKP',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(304,'Panasonic CS-C18BKP',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(305,'M890F',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(306,'NEC PlasmaSync 50XM5 PX-50XM5W',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(307,'Samsung SyncMaster 225BW',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(308,'Samsung SyncMaster 940N',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(309,'Rotel RMB-1095',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(310,'MS-Max TS 360A',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(311,'Shure PGX 24E/SM58-R1',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(312,'Wacom DTU-1631',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(313,'Sven Pro 700',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(314,'Sven Pro 500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(315,'HP Proliant DL 380G7 E',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(316,'HP Color Laser Jet CP5520',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(317,'Cisco 2940',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(318,'Cisco Catalyst 2960-48',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(319,'DLINK DCS-6410',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(320,'QNAP VS-4016U-RP Pro',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(321,'ATEN KVM CS1716I',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(322,'Cisco Catalyst 3570-48',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(323,'Cisco Catalyst 500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(324,'Eaton Evolution S',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(325,'Cisco Catalyst 3560',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(326,'APC Smart-UPS 1500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(327,'D-Link DES 3010 G',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(328,'D-Link DES-3526',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(329,'Alied Telesis AT-GS950/24',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(330,'EATON EX 1500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(331,'APC Smart-UPS RT 1000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(332,'3COM 3C 16470-B',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(333,'EATON Ellipse MAX 850',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(334,'HP Proliant DL 120 G7',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(335,'Cisco UC Phone CP9971',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(271,'Toshiba Satellite L500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(272,'DELL Latitude D820',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(273,'DELL Latitude D830',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(274,'DELL Latitude D810',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(275,'DELL Inspiron 1764',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(276,'RoverBook B510W',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(277,'Compaq ML570',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(278,'HP Proliant ML 370 G3',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(279,'HP Proliant DL380 G4',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(280,'HP Proliant ML 370 G4',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(281,'Klondake President 1500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(282,'Kraftway Express 100 EI13',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(283,'HP DJ 1055 CM Plus',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(284,'HP LJ 2430',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(285,'Epson Stylus Photo R2400',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(286,'HP LJ 2015D',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(287,'HP LJ 3052',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(288,'Aficio SP C821DN',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(337,'Xerox Phaser 6125 (color)',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(338,'HP cp1525n Color',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(339,'Canon CanoScan Lide 25',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(340,'HP Proliant DL380 G6',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(341,'Acer P7500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(342,'ELO Touch Systems ET 3239L-8CEA-O-A-G',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(343,'Draper Targa (9х16) 467/184” 229*406MW',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(344,'APC Smatr-UPS RT 1500',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(345,'ASUS N55S',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(346,'HP ProLiant DL180 G6',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(347,'HP ProLiant DL120 G6',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(348,'HP Z200 Workstation',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(349,'HP Compaq 6000 Pro SFF PC',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(350,'Intel S5520UR',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(351,'HP dc5800 SFF',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(352,'Arutek Corp i56',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(353,'Arutek Tower CC',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(354,'Kraftway Credo KC36',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(355,'Kraftway Express 100 EI15',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(356,'Industrial Computer 610H',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(357,'Sun Ultra 40',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(358,'CheckPoint UTM 570 (U-20)',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(359,'DEPO RACE X320N',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(360,'HP Scanjet N6310',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(361,'Epson GT-20000',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(9,'Ricoh Aficio FX-16',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(11,'Ricoh Aficio p7527n',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(14,'Ricoh Aficio С7425Dn',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(93,'Ricoh Aficio 2045e',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(94,'Ricoh Aficio C7010',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(145,'HP LJ Р3005N',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(261,'HP LJ 1010/1020/3010',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(262,'HP LJ 2100/2200',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(263,'HP LJ 1100/Canon LBP 1120',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(264,'HP LJ 5000/5100',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(265,'HP LJ 5p/6p',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(266,'Ricoh Aficio MP161/171/1515',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(267,'Ricoh Aficio MP2000/2020',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(268,'HP LJ 1005/1006',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(269,'Ricoh Aficio 3400/3410',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(270,'Ricoh Aficio 7132/7535',NULL)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(289,'HP LJ 5200DTN',290)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(336,'HP LaserJet 5200tn',290)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(8,'Ricoh Aficio 7132 (A3)',270)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(12,'Ricoh Aficio p7535n',270)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(244,'Ricoh Aficio 3410DN',269)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(245,'Ricoh Aficio 3400SF',269)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(256,'Ricoh Aficio 3400N',269)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(225,'HP LJ 1005',268)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(163,'HP LJ 1006',268)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(92,'Ricoh Aficio 2020D',267)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(86,'Ricoh Aficio MP2000',267)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(213,'Ricoh Aficio MP 2000 (не использовать)',267)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(229,'Ricoh Aficio MP2000LN',267)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(257,'Ricoh Aficio MP2000SP',267)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(95,'Ricoh Aficio MP161',266)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(259,'Ricoh Afico MP171SPF',266)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(228,'Ricoh Aficio MP161LN',266)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(7,'Ricoh Aficio 1515fn',266)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(91,'Ricoh Aficio 1515',266)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(66,'HP LJ 5p',265)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(67,'HP LJ 6p',265)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(64,'HP LJ 5000',264)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(65,'HP LJ 5100',264)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(18,'Canon LBP 1120',263)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(58,'HP LJ 1100',263)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(71,'HP LJ 2200DT',262)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(61,'HP LJ 2100',262)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(56,'HP LJ 1010',261)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(57,'HP LJ 1020',261)
insert into ti_mark(mark_id,mark_name,enlarge_id) values(68,'HP LJ P3005DN',145)

SET IDENTITY_INSERT ti_mark OFF
go